---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: none
ENABLE_LINTERS:
  - YAML_YAMLLINT
EXCLUDED_DIRECTORIES:
  - "node_modules"
LINTER_RULES_PATH: .
PRINT_ALPACA: false
GITHUB_STATUS_REPORTER: false
GITHUB_COMMENT_REPORTER: false
VALIDATE_ALL_CODEBASE: true
