input-file: redhatopenshift/resource-manager/Microsoft.RedHatOpenshift/preview/2024-06-10-preview/openapi.json
go:
  namespace: redhatopenshift
  project-folder: ../internal
  output-folder: $(project-folder)/api/v20240610preview
  file-prefix: generated
  module-version: "0.0.1"
  containing-module: "github.com/Azure/ARO-HCP/internal"
  azure-arm: true
  generate-fakes: true