---
name: Build/Push Frontend Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-deploy-frontend.yml'
      - 'frontend/**'
      - 'internal/**'

jobs:
  build_push_frontend:
    permissions:
      id-token: 'write'
      contents: 'read'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 1

      - name: Build frontend container image
        env:
          ARO_HCP_IMAGE_ACR: devarohcp
        run: |
          cd frontend/
          make image

      - name: 'Az CLI login'
        if: github.event.push.ref == 'refs/heads/main'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: Push frontend container image
        if: github.event.push.ref == 'refs/heads/main'
        env:
          ARO_HCP_IMAGE_ACR: devarohcp
        run: |
          cd frontend/
          az acr login --name devarohcp
          make push
