name: 'ci-go'
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - 'go.work'
jobs:
  test:
    permissions:
      contents: 'read'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 1

      - name: 'Set up Go'
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.work'
          check-latest: true

      - name: 'Test'
        run: make test
  lint:
    permissions:
      contents: 'read'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 1

      - name: 'Set up Go'
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.work'
          check-latest: true

      - name: 'Lint'
        uses: golangci/golangci-lint-action@9d1e0624a798bb64f6c3cea93db47765312263dc # v5.1.0
        with:
          version: 'v1.56.2'
          args: '-v $(go list -f ''{{.Dir}}/...'' -m | xargs)'
