name: 'ci-go'
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'
      - 'go.work'
jobs:
  test:
    permissions:
      contents: 'read'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 1

      - name: 'Set up Go'
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.work'
          check-latest: true

      - name: 'Test'
        run: make test
  lint:
    permissions:
      contents: 'read'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 1

      - name: 'Set up Go'
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.work'
          check-latest: true

      - name: 'Lint'
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4.0.0
        with:
          version: 'v1.56.2'
          args: '-v $(go list -f ''{{.Dir}}/...'' -m | xargs)'
